#!/bin/sh -x
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

. ./defs || exit 1

tempfile=`mktemp ii41-XXXXXXXX`
outputdirfile=$tempfile.gz
cp ${testdir}/ii-0041-input-dir-file.gz $outputdirfile || exit $?

# when copying in distcheck, source will be readonly.
chmod u+rw $outputdirfile || exit $?

${install_info} ${testdir}/ii-0041-input-info-file $outputdirfile || exit $?

# Simulate 'zdiff'.  zdiff on HP-UX does not support the gzip format.
expectedfile=${testdir}/ii-0041-expected-dir-file.gz
expectedfile_uncompressed=$tempfile.exp
outputdirfile_uncompressed=$tempfile.act
if cmp $expectedfile $outputdirfile >/dev/null; then
  retval=0
else
  if gzip -d -c < $expectedfile > $expectedfile_uncompressed; then
    if gzip -d -c < $outputdirfile > $outputdirfile_uncompressed; then
      diff $expectedfile_uncompressed $outputdirfile_uncompressed
      retval=$?
    else
      # $outputdirfile is not in gzip format
      retval=1
    fi
  else
    # gzip not found or not working
    retval=77
  fi
fi

rm -f $tempfile $outputdirfile $expectedfile_uncompressed $outputdirfile_uncompressed
exit $retval
