#!/bin/sh -x
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

. ./defs || exit 1

tempfile=`mktemp ii50-XXXXXXXX`
outputdirfile=$tempfile.gz
cp ${testdir}/ii-0050-input-dir-file.gz $outputdirfile || exit $?

# when copying in distcheck, source will be readonly.
chmod u+rw $outputdirfile || exit $?

${install_info} --remove ${testdir}/ii-0050-input-info-file $outputdirfile \
|| exit $?

if findprog zdiff; then
  zdiff ${testdir}/ii-0050-expected-dir-file.gz $outputdirfile
  retval=$?
else
  retval=77
fi

rm -f $tempfile $outputdirfile
exit $retval
