\input texinfo @c -*-texinfo-*-
@setfilename formatting-regions.info

@documentdescription
This is the explicit d--ocument @code{d@'escription}.
@end documentdescription

@node Top
@top Top section
@ifnothtml

@menu
* constructs::
* chapter::               chapter

Menu comment

* chapter2:description.   Chapter 2
@end menu

@end ifnothtml
@node constructs
@chapter constructs

@include coverage_macro.texi

@copying
@mymacro{}
@end copying

@titlepage
@title title --a
@subtitle formatting subtitle --a
@subtitle subtitle 2 --a
@author author1 --a with accents in name T@'e@,ca
@author author2 --a

Titlepage
@mymacro{}

insertcopying in titlepage
@insertcopying
end titlepage
@end titlepage

@mymacro{}

@example
@mymacro{}
@end example

insertcopying
@insertcopying

@cindex t--ruc
@cindex T--ruc
@cindex .
@cindex ?
@cindex a
@findex t--ruc
@findex T--ruc
@findex .
@findex ?
@findex a


cp
@printindex cp

fn
@printindex fn

vr
@printindex vr

ky
@printindex ky

pg
@printindex pg

tp
@printindex tp



@node chapter
@chapter chapter

@footnote{in footnote}

@format
@menu 
* s--ect@comma{}ion:: s--ect@comma{}ion

Menu comment
``simple-double--three---four----''@*

@end menu
@end format

@node s--ect@comma{}ion
@section A section

@menu
* subsection:: 
@end menu

@node subsection
@subsection subsection

@menu
* subsubsection::
@end menu

@anchor{anchor}

@node subsubsection
@subsubsection subsubsection

@node chapter2
@centerchap chapter 2

@printindex cp
@printindex fn

@contents
@shortcontents
