#! /bin/sh
# $Id: parser_base_tests,v 1.5 2012/11/13 18:30:38 karl Exp $
# Copyright 2010, 2012 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

if test z"$srcdir" = 'z'; then
  srcdir=.
fi

if test "z$LONG_TESTS" = z'yes'; then
  echo "Skipping short tests because we are only doing long tests"
  exit 77
fi

"$srcdir"/parser_tests.sh "$@" \
 formatting \
 htmlxref htmlxref-only_mono htmlxref-only_split
