/* This file automatically generated by command_data.awk */
/* global_unique in command_data.txt */

GLOBAL_UNIQUE_CASE(afivepaper);
GLOBAL_UNIQUE_CASE(afourlatex);
GLOBAL_UNIQUE_CASE(afourpaper);
GLOBAL_UNIQUE_CASE(afourwide);
GLOBAL_UNIQUE_CASE(bsixpaper);
GLOBAL_UNIQUE_CASE(copying);
GLOBAL_UNIQUE_CASE(documentdescription);
GLOBAL_UNIQUE_CASE(evenfooting);
GLOBAL_UNIQUE_CASE(evenfootingmarks);
GLOBAL_UNIQUE_CASE(evenheading);
GLOBAL_UNIQUE_CASE(evenheadingmarks);
GLOBAL_UNIQUE_CASE(everyfooting);
GLOBAL_UNIQUE_CASE(everyfootingmarks);
GLOBAL_UNIQUE_CASE(everyheading);
GLOBAL_UNIQUE_CASE(everyheadingmarks);
GLOBAL_UNIQUE_CASE(fonttextsize);
GLOBAL_UNIQUE_CASE(footnotestyle);
GLOBAL_UNIQUE_CASE(novalidate);
GLOBAL_UNIQUE_CASE(oddfooting);
GLOBAL_UNIQUE_CASE(oddfootingmarks);
GLOBAL_UNIQUE_CASE(oddheading);
GLOBAL_UNIQUE_CASE(oddheadingmarks);
GLOBAL_UNIQUE_CASE(pagesizes);
GLOBAL_UNIQUE_CASE(setchapternewpage);
GLOBAL_UNIQUE_CASE(settitle);
GLOBAL_UNIQUE_CASE(shorttitlepage);
GLOBAL_UNIQUE_CASE(smallbook);
GLOBAL_UNIQUE_CASE(title);
GLOBAL_UNIQUE_CASE(titlepage);
GLOBAL_UNIQUE_CASE(top);
