/* This file automatically generated by command_data.awk */
#ifndef GLOBAL_COMMANDS_TYPES_H
#define GLOBAL_COMMANDS_TYPES_H

#include "tree_types.h"

typedef struct GLOBAL_COMMANDS {
    /* Elements that should be unique. */
   ELEMENT *afivepaper;
   ELEMENT *afourlatex;
   ELEMENT *afourpaper;
   ELEMENT *afourwide;
   ELEMENT *bsixpaper;
   ELEMENT *copying;
   ELEMENT *documentdescription;
   ELEMENT *evenfooting;
   ELEMENT *evenfootingmarks;
   ELEMENT *evenheading;
   ELEMENT *evenheadingmarks;
   ELEMENT *everyfooting;
   ELEMENT *everyfootingmarks;
   ELEMENT *everyheading;
   ELEMENT *everyheadingmarks;
   ELEMENT *fonttextsize;
   ELEMENT *footnotestyle;
   ELEMENT *novalidate;
   ELEMENT *oddfooting;
   ELEMENT *oddfootingmarks;
   ELEMENT *oddheading;
   ELEMENT *oddheadingmarks;
   ELEMENT *pagesizes;
   ELEMENT *setchapternewpage;
   ELEMENT *setfilename;
   ELEMENT *settitle;
   ELEMENT *shorttitlepage;
   ELEMENT *smallbook;
   ELEMENT *title;
   ELEMENT *titlepage;
   ELEMENT *top;

   /* Arrays of elements */
   ELEMENT_LIST dircategory_direntry;

   ELEMENT_LIST floats;
   ELEMENT_LIST footnotes;

   ELEMENT_LIST allowcodebreaks;
   ELEMENT_LIST author;
   ELEMENT_LIST chapheading;
   ELEMENT_LIST clickstyle;
   ELEMENT_LIST codequotebacktick;
   ELEMENT_LIST codequoteundirected;
   ELEMENT_LIST contents;
   ELEMENT_LIST deftypefnnewline;
   ELEMENT_LIST detailmenu;
   ELEMENT_LIST documentencoding;
   ELEMENT_LIST documentlanguage;
   ELEMENT_LIST exampleindent;
   ELEMENT_LIST firstparagraphindent;
   ELEMENT_LIST frenchspacing;
   ELEMENT_LIST heading;
   ELEMENT_LIST headings;
   ELEMENT_LIST hyphenation;
   ELEMENT_LIST insertcopying;
   ELEMENT_LIST kbdinputstyle;
   ELEMENT_LIST listoffloats;
   ELEMENT_LIST majorheading;
   ELEMENT_LIST microtype;
   ELEMENT_LIST paragraphindent;
   ELEMENT_LIST part;
   ELEMENT_LIST printindex;
   ELEMENT_LIST shortcontents;
   ELEMENT_LIST subheading;
   ELEMENT_LIST subsubheading;
   ELEMENT_LIST subtitle;
   ELEMENT_LIST summarycontents;
   ELEMENT_LIST titlefont;
   ELEMENT_LIST urefbreakstyle;
   ELEMENT_LIST xrefautomaticsectiontitle;

} GLOBAL_COMMANDS;

#endif
