/* This file automatically generated by command_data.awk */
/* global in command_data.txt */

GLOBAL_CASE(allowcodebreaks);
GLOBAL_CASE(author);
GLOBAL_CASE(chapheading);
GLOBAL_CASE(clickstyle);
GLOBAL_CASE(codequotebacktick);
GLOBAL_CASE(codequoteundirected);
GLOBAL_CASE(contents);
GLOBAL_CASE(deftypefnnewline);
GLOBAL_CASE(detailmenu);
GLOBAL_CASE(documentencoding);
GLOBAL_CASE(documentlanguage);
GLOBAL_CASE(exampleindent);
GLOBAL_CASE(firstparagraphindent);
GLOBAL_CASE(frenchspacing);
GLOBAL_CASE(heading);
GLOBAL_CASE(headings);
GLOBAL_CASE(hyphenation);
GLOBAL_CASE(insertcopying);
GLOBAL_CASE(kbdinputstyle);
GLOBAL_CASE(listoffloats);
GLOBAL_CASE(majorheading);
GLOBAL_CASE(microtype);
GLOBAL_CASE(paragraphindent);
GLOBAL_CASE(part);
GLOBAL_CASE(printindex);
GLOBAL_CASE(shortcontents);
GLOBAL_CASE(subheading);
GLOBAL_CASE(subsubheading);
GLOBAL_CASE(subtitle);
GLOBAL_CASE(summarycontents);
GLOBAL_CASE(titlefont);
GLOBAL_CASE(urefbreakstyle);
GLOBAL_CASE(xrefautomaticsectiontitle);
