#! /bin/sh
# Copyright 2011-2019 Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Original author: Patrice Dumas.
 
# Script to strip Texinfo commands.  It is so trivial we don't install
# it, but it's in the distribution as an example.
#
exec texi2any --set-customization-variable TEXINFO_OUTPUT_FORMAT=textcontent "$@"
