#! /bin/sh
# $Id: texi2html 5191 2013-02-23 00:11:18Z karl $
# Copyright 2012 Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Original author: Patrice Dumas.
 
# Convert Texinfo to HTML, setting the default style to be the texi2html
# style.
#
# It is not fully compatible with texi2html.  There is no possibility of
# splitting indices, and translated strings cannot (yet?) be customized.
# Command line processing and options have also changed, and the
# customization API is new.
# 
# Thus, since this is not a drop-in replacement for the old texi2html,
# we do not install it.  It's here as an example.
# 
# See the texi2html node in the Texinfo manual for more.
#
exec texi2any --set-init-variable TEXI2HTML=1 "$@"

