@node Texinfo@asis{::}Convert@asis{::}Plaintext
@chapter Texinfo::Convert::Plaintext

@node Texinfo@asis{::}Convert@asis{::}Plaintext NAME
@section Texinfo::Convert::Plaintext NAME

Texinfo::Convert::Plaintext - Convert Texinfo tree to Plaintext

@node Texinfo@asis{::}Convert@asis{::}Plaintext SYNOPSIS
@section Texinfo::Convert::Plaintext SYNOPSIS

@verbatim
  my $converter
    = Texinfo::Convert::Plaintext->converter({'NUMBER_SECTIONS' => 0});

  $converter->output($document);
  $converter->convert($document);
  $converter->convert_tree($tree);
@end verbatim

@node Texinfo@asis{::}Convert@asis{::}Plaintext NOTES
@section Texinfo::Convert::Plaintext NOTES

The Texinfo Perl module main purpose is to be used in @code{texi2any} to convert
Texinfo to other formats.  There is no promise of API stability.

@node Texinfo@asis{::}Convert@asis{::}Plaintext DESCRIPTION
@section Texinfo::Convert::Plaintext DESCRIPTION

Texinfo::Convert::Plaintext converts a Texinfo tree to Plaintext.

@node Texinfo@asis{::}Convert@asis{::}Plaintext METHODS
@section Texinfo::Convert::Plaintext METHODS

@table @asis
@item $converter = Texinfo::Convert::Plaintext->converter($options)
@anchor{Texinfo@asis{::}Convert@asis{::}Plaintext $converter = Texinfo@asis{::}Convert@asis{::}Plaintext->converter($options)}

Initialize converter from Texinfo to Plaintext.

The @emph{$options} hash reference holds Texinfo customization options for the
converter.  These options should be Texinfo customization options
that can be passed to the converter.  Most of the customization options are
described in the Texinfo manual or in the customization API manual.  Those
customization options, when appropriate, override the document content.

See @ref{Texinfo@asis{::}Convert@asis{::}Converter NAME,, Texinfo::Convert::Converter} for more information.

@item $converter->output($document)
@anchor{Texinfo@asis{::}Convert@asis{::}Plaintext $converter->output($document)}

Convert a Texinfo parsed document @emph{$document} and output the result in files as
described in the Texinfo manual.

@item $result = $converter->convert($document)
@anchor{Texinfo@asis{::}Convert@asis{::}Plaintext $result = $converter->convert($document)}

Convert a Texinfo parsed document @emph{$document} and return the resulting output.

@item $result = $converter->convert_tree($tree)
@anchor{Texinfo@asis{::}Convert@asis{::}Plaintext $result = $converter->convert_tree($tree)}

Convert a Texinfo tree portion @emph{$tree} and return the resulting
output.  This function does not try to output a full document but only
portions.  For a full document use @code{convert}.

In general, this function should be called after the converter has been
associated to a document by a call to @code{output} or @code{convert}.

@end table

@node Texinfo@asis{::}Convert@asis{::}Plaintext AUTHOR
@section Texinfo::Convert::Plaintext AUTHOR

Patrice Dumas, <pertusus@@free.fr>

@node Texinfo@asis{::}Convert@asis{::}Plaintext COPYRIGHT AND LICENSE
@section Texinfo::Convert::Plaintext COPYRIGHT AND LICENSE

Copyright 2010- Free Software Foundation, Inc.  See the source file for
all copyright years.

This library is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

