@node Texinfo::Convert::DocBook
@chapter Texinfo::Convert::DocBook

@menu
* Texinfo@asis{::}Convert@asis{::}DocBook NAME::
* Texinfo@asis{::}Convert@asis{::}DocBook SYNOPSIS::
* Texinfo@asis{::}Convert@asis{::}DocBook DESCRIPTION::
* Texinfo@asis{::}Convert@asis{::}DocBook METHODS::
* Texinfo@asis{::}Convert@asis{::}DocBook AUTHOR::
@end menu

@node Texinfo::Convert::DocBook NAME
@section NAME

Texinfo::Convert::DocBook - Convert Texinfo tree to DocBook

@node Texinfo::Convert::DocBook SYNOPSIS
@section SYNOPSIS

@verbatim
  my $converter 
    = Texinfo::Convert::DocBook->converter({'parser' => $parser});

  $converter->output($tree);
  $converter->convert($tree);
  $converter->convert_tree($tree);
@end verbatim

@node Texinfo::Convert::DocBook DESCRIPTION
@section DESCRIPTION

Texinfo::Convert::DocBook converts a Texinfo tree to DocBook.

@node Texinfo::Convert::DocBook METHODS
@section METHODS

@table @asis
@item $converter = Texinfo::Convert::DocBook->converter($options)
@anchor{Texinfo::Convert::DocBook $converter = Texinfo::Convert::DocBook->converter($options)}

Initialize converter from Texinfo to DocBook.  

The @emph{$options} hash reference holds options for the converter.  In
this option hash reference a parser object may be associated with the 
@emph{parser} key.  The other options should be configuration options
described in the Texinfo manual.  Those options, when appropriate,
override the document content.

See @ref{Texinfo::Convert::Converter NAME} for more informations.

@item $converter->output($tree)
@anchor{Texinfo::Convert::DocBook $converter->output($tree)}

Convert a Texinfo tree @emph{$tree} and output the result in files as
described in the Texinfo manual.

@item $result = $converter->convert($tree)
@anchor{Texinfo::Convert::DocBook $result = $converter->convert($tree)}

Convert a Texinfo tree @emph{$tree} or tree portion and return 
the resulting output.

@item $result = $converter->convert_tree($tree)
@anchor{Texinfo::Convert::DocBook $result = $converter->convert_tree($tree)}

Convert a Texinfo tree portion @emph{$tree} and return the resulting 
output.  This function does not try to output a full document but only
portions.  For a full document use @code{convert}.

@end table

@node Texinfo::Convert::DocBook AUTHOR
@section AUTHOR

Patrice Dumas, <pertusus@@free.fr>

