@node Texinfo::Convert::TexinfoXML
@chapter Texinfo::Convert::TexinfoXML

@menu
* Texinfo@asis{::}Convert@asis{::}TexinfoXML NAME::
* Texinfo@asis{::}Convert@asis{::}TexinfoXML SYNOPSIS::
* Texinfo@asis{::}Convert@asis{::}TexinfoXML DESCRIPTION::
* Texinfo@asis{::}Convert@asis{::}TexinfoXML METHODS::
* Texinfo@asis{::}Convert@asis{::}TexinfoXML AUTHOR::
@end menu

@node Texinfo::Convert::TexinfoXML NAME
@section NAME

Texinfo::Convert::TexinfoXML - Convert Texinfo tree to TexinfoXML

@node Texinfo::Convert::TexinfoXML SYNOPSIS
@section SYNOPSIS

@verbatim
  my $converter 
    = Texinfo::Convert::TexinfoXML->converter({'parser' => $parser});

  $converter->output($tree);
  $converter->convert($tree);
  $converter->convert_tree($tree);
@end verbatim

@node Texinfo::Convert::TexinfoXML DESCRIPTION
@section DESCRIPTION

Texinfo::Convert::TexinfoXML converts a Texinfo tree to TexinfoXML.

@node Texinfo::Convert::TexinfoXML METHODS
@section METHODS

@table @asis
@item $converter = Texinfo::Convert::TexinfoXML->converter($options)
@anchor{Texinfo::Convert::TexinfoXML $converter = Texinfo::Convert::TexinfoXML->converter($options)}

Initialize converter from Texinfo to TexinfoXML.  

The @emph{$options} hash reference holds options for the converter.  In
this option hash reference a parser object may be associated with the 
@emph{parser} key.  The other options should be configuration options
described in the Texinfo manual.  Those options, when appropriate,
override the document content.

See @ref{Texinfo::Convert::Converter NAME} for more informations.

@item $converter->output($tree)
@anchor{Texinfo::Convert::TexinfoXML $converter->output($tree)}

Convert a Texinfo tree @emph{$tree} and output the result in files as
described in the Texinfo manual.

@item $result = $converter->convert($tree)
@anchor{Texinfo::Convert::TexinfoXML $result = $converter->convert($tree)}

Convert a Texinfo tree @emph{$tree} or tree portion and return 
the resulting output.

@item $result = $converter->convert_tree($tree)
@anchor{Texinfo::Convert::TexinfoXML $result = $converter->convert_tree($tree)}

Convert a Texinfo tree portion @emph{$tree} and return the resulting 
output.  This function does not try to output a full document but only
portions.  For a full document use @code{convert}.

@end table

@node Texinfo::Convert::TexinfoXML AUTHOR
@section AUTHOR

Patrice Dumas, <pertusus@@free.fr>

