@node Texinfo::Convert::Info
@chapter Texinfo::Convert::Info

@menu
* Texinfo@asis{::}Convert@asis{::}Info NAME::
* Texinfo@asis{::}Convert@asis{::}Info SYNOPSIS::
* Texinfo@asis{::}Convert@asis{::}Info DESCRIPTION::
* Texinfo@asis{::}Convert@asis{::}Info METHODS::
* Texinfo@asis{::}Convert@asis{::}Info AUTHOR::
@end menu

@node Texinfo::Convert::Info NAME
@section NAME

Texinfo::Convert::Info - Convert Texinfo tree to Info

@node Texinfo::Convert::Info SYNOPSIS
@section SYNOPSIS

@verbatim
  my $converter 
    = Texinfo::Convert::Info->converter({'parser' => $parser});

  $converter->output($tree);
  $converter->convert($tree);
  $converter->convert_tree($tree);
@end verbatim

@node Texinfo::Convert::Info DESCRIPTION
@section DESCRIPTION

Texinfo::Convert::Info converts a Texinfo tree to Info.

@node Texinfo::Convert::Info METHODS
@section METHODS

@table @asis
@item $converter = Texinfo::Convert::Info->converter($options)
@anchor{Texinfo::Convert::Info $converter = Texinfo::Convert::Info->converter($options)}

Initialize converter from Texinfo to Info.  

The @emph{$options} hash reference holds options for the converter.  In
this option hash reference a parser object may be associated with the 
@emph{parser} key.  The other options should be configuration options
described in the Texinfo manual.  Those options, when appropriate,
override the document content.

See @ref{Texinfo::Convert::Converter NAME} for more informations.

@item $converter->output($tree)
@anchor{Texinfo::Convert::Info $converter->output($tree)}

Convert a Texinfo tree @emph{$tree} and output the result in files as
described in the Texinfo manual.

@item $result = $converter->convert($tree)
@anchor{Texinfo::Convert::Info $result = $converter->convert($tree)}

Convert a Texinfo tree @emph{$tree} or tree portion and return 
the resulting output.

@item $result = $converter->convert_tree($tree)
@anchor{Texinfo::Convert::Info $result = $converter->convert_tree($tree)}

Convert a Texinfo tree portion @emph{$tree} and return the resulting 
output.  This function does not try to output a full document but only
portions.  For a full document use @code{convert}.

@end table

@node Texinfo::Convert::Info AUTHOR
@section AUTHOR

Patrice Dumas, <pertusus@@free.fr>

